export const DATA = {
  "spice-merchant": {
    href: "/kitchen/spice-merchant",
    title: "The Spice Merchant",
    description: "Authentic Indian cuisine with a focus on hygiene. Rated 4.5 stars.",
    mainImage: "/images/spice-merchant-main.jpg",

    name: "The Spice Merchant",
    address: "12 MG Road, Bengaluru, Karnataka",
    rating: 4.5,
    ratingsCount: 120,
    hero: "/images/spice-merchant1.jpg",
    images: [
      "/images/spice-merchant1.jpg",
      "/images/spice-merchant2.jpg",
      "/images/spice-merchant3.jpg",
      "/images/spice-merchant4.jpg",
    ],
    menu: [
      {
        name: "Chicken Biryani",
        desc: "Aromatic basmati rice cooked with tender chicken pieces and traditional spices.",
        price: "₹249",
        img: "/images/chicken-biryani-bowl.jpg",
      },
      {
        name: "Paneer Butter Masala",
        desc: "Soft cottage cheese cubes in a creamy tomato-based gravy.",
        price: "₹199",
        img: "/images/paneer-butter-masala.jpg",
      },
      {
        name: "Tandoori Roti",
        desc: "Crisp whole wheat flatbread cooked in a traditional clay oven.",
        price: "₹45",
        img: "/images/tandoori-roti.jpg",
      },
      {
        name: "Gulab Jamun",
        desc: "Deep-fried milk solids soaked in rose-flavored syrup.",
        price: "₹99",
        img: "/images/gulab-jamun.jpg",
      },
    ],
    owner: { name: "Rajesh Patel", avatar: "/images/rajesh.png" },
    reviews: [
      { user: "Ananya Sharma", rating: 5, text: "Delicious food and great hygiene!" },
      { user: "Ravi Mehta", rating: 4, text: "Paneer Butter Masala was outstanding." },
      { user: "Kavya Nair", rating: 4, text: "Nice ambience, biryani could be spicier." },
      { user: "Arjun Verma", rating: 5, text: "Authentic flavors, will visit again." },
      { user: "Sneha Iyer", rating: 5, text: "Gulab Jamun was heavenly!" },
    ],
    distribution: [
      { label: "5", percent: 40 },
      { label: "4", percent: 30 },
      { label: "3", percent: 15 },
      { label: "2", percent: 10 },
      { label: "1", percent: 5 },
    ],
    location: { lat: 12.9716, lng: 77.5946 },
  },

  "pasta-paradise": {
    href: "/kitchen/pasta-paradise",
    title: "Pasta Paradise",
    description: "Italian dishes made with fresh ingredients. Verified kitchen. Rated 4.2 stars.",
    mainImage: "/images/pasta-paradise-main.jpg",

    name: "Pasta Paradise",
    address: "22 Carter Road, Bandra, Mumbai, Maharashtra",
    rating: 4.2,
    ratingsCount: 98,
    hero: "/images/pasta-paradise1.jpg",
    images: [
      "/images/pasta-paradise1.jpg",
      "/images/pasta-paradise2.jpg",
      "/images/pasta-paradise3.jpg",
    ],
    menu: [
      {
        name: "Penne Arrabiata",
        desc: "Pasta tossed in spicy tomato sauce with chili flakes and olive oil.",
        price: "₹349",
        img: "/images/penne-arrabiata.jpg",
      },
      {
        name: "Fettuccine Alfredo",
        desc: "Creamy pasta with parmesan cheese and garlic sauce.",
        price: "₹399",
        img: "/images/fettuccine-alfredo.jpg",
      },
      {
        name: "Margherita Pizza",
        desc: "Classic thin-crust pizza topped with mozzarella and basil.",
        price: "₹499",
        img: "/images/margherita-pizza.jpg",
      },
      {
        name: "Tiramisu",
        desc: "Layered Italian dessert with mascarpone and espresso.",
        price: "₹299",
        img: "/images/tiramisu.jpg",
      },
    ],
    owner: { name: "Giovanni Rossi", avatar: "/images/giovanni.png" },
    reviews: [
      { user: "Simran Kaur", rating: 5, text: "Loved the Alfredo pasta!" },
      { user: "Aarav Kapoor", rating: 4, text: "Pizza was amazing, but a bit expensive." },
      { user: "Meera Das", rating: 5, text: "Best Italian food in Mumbai." },
      { user: "Dev Patel", rating: 4, text: "Tiramisu was fresh and creamy." },
      { user: "Nisha Reddy", rating: 3, text: "Good food, service could improve." },
    ],
    distribution: [
      { label: "5", percent: 35 },
      { label: "4", percent: 40 },
      { label: "3", percent: 15 },
      { label: "2", percent: 5 },
      { label: "1", percent: 5 },
    ],
    location: { lat: 19.0593, lng: 72.8295 },
  },

  "sushi-central": {
    href: "/kitchen/sushi-central",
    title: "Sushi Central",
    description: "Fresh sushi and Japanese cuisine. High hygiene standards. Rated 4.8 stars.",
    mainImage: "/images/sushi-central-main.jpg",

    name: "Sushi Central",
    address: "8 Park Street, Kolkata, West Bengal",
    rating: 4.8,
    ratingsCount: 210,
    hero: "/images/sushi-central1.jpg",
    images: [
      "/images/sushi-central1.jpg",
      "/images/sushi-central2.jpg",
      "/images/sushi-central3.jpg",
      "/images/sushi-central4.jpg",
    ],
    menu: [
      {
        name: "Salmon Nigiri",
        desc: "Fresh salmon slices over seasoned rice.",
        price: "₹499",
        img: "/images/salmon-nigiri.jpg",
      },
      {
        name: "California Roll",
        desc: "Crab, avocado, and cucumber roll topped with sesame seeds.",
        price: "₹449",
        img: "/images/california-roll.jpg",
      },
      {
        name: "Tempura Prawns",
        desc: "Crispy battered prawns served with soy dip.",
        price: "₹599",
        img: "/images/tempura-prawns.jpg",
      },
      {
        name: "Miso Soup",
        desc: "Traditional Japanese soup with tofu and seaweed.",
        price: "₹199",
        img: "/images/miso-soup.jpg",
      },
    ],
    owner: { name: "Aiko Tanaka", avatar: "/images/aiko.png" },
    reviews: [
      { user: "Rahul Sen", rating: 5, text: "The sushi was unbelievably fresh!" },
      { user: "Pooja Nair", rating: 5, text: "Loved the ambiance and service." },
      { user: "Manish Ghosh", rating: 4, text: "Tempura was crisp and perfect." },
      { user: "Ritika Basu", rating: 5, text: "Best sushi I've had in India." },
      { user: "Kiran Jha", rating: 4, text: "Authentic taste, slightly pricey." },
    ],
    distribution: [
      { label: "5", percent: 60 },
      { label: "4", percent: 25 },
      { label: "3", percent: 10 },
      { label: "2", percent: 3 },
      { label: "1", percent: 2 },
    ],
    location: { lat: 22.5524, lng: 88.3535 },
  },

  "burger-barn": {
    href: "/kitchen/burger-barn",
    title: "Burger Barn",
    description: "Gourmet burgers and sides. Verified for cleanliness. Rated 4.0 stars.",
    mainImage: "/images/gourmet-burger.png",

    name: "Burger Barn",
    address: "34 Connaught Place, New Delhi",
    rating: 4.0,
    ratingsCount: 75,
    hero: "/images/burger-barn1.jpg",
    images: [
      "/images/burger-barn1.jpg",
      "/images/burger-barn2.jpg",
      "/images/burger-barn3.jpg",
    ],
    menu: [
      {
        name: "Classic Cheeseburger",
        desc: "Juicy beef patty with melted cheese and lettuce.",
        price: "₹299",
        img: "/images/classic-cheeseburger.jpg",
      },
      {
        name: "Spicy Chicken Burger",
        desc: "Crispy chicken fillet with spicy mayo and lettuce.",
        price: "₹279",
        img: "/images/spicy-chicken-burger.jpg",
      },
      {
        name: "Veg Supreme Burger",
        desc: "Loaded vegetable patty with cheese and jalapeños.",
        price: "₹249",
        img: "/images/veg-supreme-burger.jpg",
      },
      {
        name: "French Fries",
        desc: "Crispy golden fries with a hint of salt.",
        price: "₹129",
        img: "/images/french-fries.jpg",
      },
    ],
    owner: { name: "Rohit Malhotra", avatar: "/images/rohit.png" },
    reviews: [
      { user: "Aditi Mishra", rating: 4, text: "Good taste and fast service." },
      { user: "Vikram Singh", rating: 5, text: "Loved the spicy chicken burger!" },
      { user: "Snehal Patel", rating: 3, text: "Fries could be crunchier." },
      { user: "Karan Joshi", rating: 4, text: "Reasonably priced and tasty." },
      { user: "Riya Sharma", rating: 4, text: "Nice burgers, cozy spot." },
    ],
    distribution: [
      { label: "5", percent: 25 },
      { label: "4", percent: 45 },
      { label: "3", percent: 20 },
      { label: "2", percent: 5 },
      { label: "1", percent: 5 },
    ],
    location: { lat: 28.6304, lng: 77.2177 },
  },
};
